//SE DEFINEN CONSTANTES QUE DESPUES SERAN UTILIZADAS EN EL SEARCH.JS DE /REDUX/ACTION

export const SEARCH_MOVIE_START ='SEARCH_MOVIE_START';
export const SEARCH_MOVIE_ERROR ='SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_COMPLETE ='SEARCH_MOVIE_COMPLETE';